name: Build universal pkg
on:
  push:
    branches:
    - update-finish
    paths-ignore:
    - '**/README.md'

jobs:
  build:
    runs-on: macos-11

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install munkipkg
      run: | 
        munki_pkg_dir=$(mktemp -d -t 'munki_pkg_dir')
        curl -L https://raw.githubusercontent.com/munki/munki-pkg/main/munkipkg --output munkipkg
        chmod +x munkipkg
        export PATH="$PATH:$pwd"
        
    - name: Build pkg
      run: |
        cd sal-scripts; swift build -c release --arch arm64 --arch x86_64
        xcodebuild -project "${GITHUB_WORKSPACE}"/report_broken_client/report_broken_client.xcodeproj -configuration Release
        cd ../
        ls -laGh sal-scripts/.build/apple/Products/*
        ls -laGh sal-scripts/.build/apple/Products/Release/*
        mv report_broken_client/build/Release/report_broken_client payload/usr/local/munki/report_broken_client
        mv sal-scripts/.build/apple/Products/Release/sal-scripts payload/usr/local/sal/bin/sal-submit
        munkipkg .

    - name: get environment variables
      id: get_env_var
      run: |
          echo "PKG_VERSION=$(cat build-info.json| jq -r .version)" >> $GITHUB_ENV

    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@e5306b306fa2e34f05258789e0e5c526c1bd4352 # v1.0.0
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{env.PKG_VERSION}}
        release_name: sal-scripts-${{env.PKG_VERSION}}.pkg
        body: |
            # Notes
            This is still in beta.
              * cert based auth has not been tested
              * running plugins will fail because the python interpreter is missing.
            # Changes
            ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Upload packages
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: build/
